function [layers,options]=setParametersNetwork(nVar,num_hidden)
%  Train LSTM network and set parameters of network
%    Input parameters:  nVar -number of time series;
%    Output parameters: layers, options - network parameters; 
%   Last modified Elena 27/11/2019
%------------------------------------------------------------------------

% Set the parameters for LSTM network

numFeatures = nVar;
numResponses = nVar;
numHiddenUnits = num_hidden;

layers = [ ...
    sequenceInputLayer(numFeatures)
    lstmLayer(numHiddenUnits)
%     dropoutLayer(0.7)
%     lstmLayer(numHiddenUnits)
%     dropoutLayer(0.7)
%     lstmLayer(numHiddenUnits)
    dropoutLayer(0.7)
    fullyConnectedLayer(numResponses)
    regressionLayer];
options = trainingOptions('sgdm', ...
    'MaxEpochs',120, ...
    'GradientThreshold',1, ...
    'InitialLearnRate',0.01, ...
    'LearnRateSchedule','piecewise', ...
    'LearnRateDropPeriod',125, ...
    'LearnRateDropFactor',0.2, ...
    'Plots','training-progress',...
    'Verbose',0);% ...
% options = trainingOptions('sgdm', ...
%     'MaxEpochs',20, ...
%     'InitialLearnRate',0.01, ...
%     'LearnRateSchedule','piecewise', ...
%     'LearnRateDropFactor',0.2, ...
%     'Plots','training-progress',...
%     'Verbose',0);% ...